services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - ./.postgres:/var/lib/postgresql

  open-observe:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: open-observe
    restart: always
    ports:
      - "5080:5080"
    env_file:
      - .env.local
    volumes:
      - ./.openobserve:/data
