receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  otlp_grpc/openobserve:
    endpoint: open-observe:5081
    headers:
      Authorization: "Basic ${env:OPENOBSERVE_AUTH_TOKEN}"
      organization: "default"
      stream-name: "test-stream"
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp_grpc/openobserve]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp_grpc/openobserve]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp_grpc/openobserve]
