export enum TelemetryIdentifier {
  TraceId = 'trace.id',
  TraceFlags = 'trace.flags',
  SpanId = 'span.id',
  WorkerEvent = 'worker.event',
  WorkerJobId = 'worker.job.id',
  WorkerJobName = 'worker.job.name',
  WorkerJobAttempt = 'worker.job.attempt',
  WorkerJobDuration = 'worker.job.duration',
  WorkerJobReason = 'worker.job.reason',
  MovieRefId = 'movie.ref_id',
  MovieId = 'movie.id',
  MovieLanguage = 'movie.language',
  PerformanceRefId = 'performance.ref_id',
  AttributeCategory = 'attribute.category',
  AttributeKey = 'attribute.key',
  UserId = 'user.id',
  NotificationId = 'notification.id',
  ServiceModuleName = 'service_module.name',
}
